package fermyon:spin-test;

/// All the imports supplied to a `spin-test` compliant test
world test-imports {
    import fermyon:spin-test-virt/key-value;
    import fermyon:spin-test-virt/sqlite;
    import fermyon:spin-wasi-virt/http-handler;
    import wasi:http/incoming-handler@0.2.0;
    import http-helper;
}

/// A `spin-test` compliant test
world test {
    include test-imports;
    export list-tests: func() -> list<string>;
    export run: func(name: string);
}

/// A test runner where the "run" function(s) are not known until runtime
world dynamic-runner {
    /// Supply the `spin.toml` manifest
    import get-manifest: func() -> string;

    /// Control the filesystem
    export fermyon:spin-wasi-virt/fs-handler;
}

world virtualized-app {
    import get-manifest: func() -> string;
    
    export wasi:clocks/monotonic-clock@0.2.0;
    export wasi:io/streams@0.2.0;
    export wasi:io/error@0.2.0;
    export wasi:io/poll@0.2.0;
    export wasi:http/types@0.2.0;
    export wasi:http/incoming-handler@0.2.0;
    export fermyon:spin-wasi-virt/http-helper;
    export fermyon:spin-wasi-virt/http-handler;
}

/// A test runner that can run a `spin-test` test composition
world runner {
    /// Include all dynamic runner items
    include dynamic-runner;
    
    /// Run the test
    export run: func(name: string);
}

/// Helpers for overcoming the limitations of `wasi:http@0.2.0`
interface http-helper {
    use wasi:http/types@0.2.0.{
        incoming-request, incoming-response, outgoing-response,
        outgoing-request, response-outparam, future-incoming-response,
        incoming-body
    };
    /// A receiver of an `incoming-response`
    resource response-receiver {
        get: func() -> option<incoming-response>;
    }
    /// Create an `incoming-request` from an `outgoing-request`
    ///
    /// An optional `incoming-body` can also be supplied which will be
    /// used instead of the body of the `outgoing-request`.
    new-request: func(request: outgoing-request, incoming-body: option<incoming-body>) -> incoming-request;
    /// Get a pair of a `response-outparam` and a `response-receiver`
    new-response: func() -> tuple<response-outparam, response-receiver>;
}