package fermyon:spin-test;

world test {
    import fermyon:spin/key-value@2.0.0;
    import fermyon:spin-test-virt/http-handler;
    import fermyon:spin-test-virt/key-value-calls;
    import wasi:http/incoming-handler@0.2.0;
    import http-helper;
    export run: func();
}

world runner {
    import get-manifest: func() -> string;
    import http-helper;
    export run: func();
}

interface http-helper {
    use wasi:http/types@0.2.0.{incoming-request, response-outparam, outgoing-response};
    resource response-receiver {
        get: func() -> option<outgoing-response>;
    }
    new-request: func() -> incoming-request;
    new-response: func() -> tuple<response-outparam, response-receiver>;
}