package fermyon:spin-virt;

/// The exports that can be composed with a Spin app creating
/// a virtualized component.
world plug {
    export fermyon:spin/key-value@2.0.0;
    export fermyon:spin/llm@2.0.0;
    export wasi:http/outgoing-handler@0.2.0;

    include config;
}

world config {
    export fermyon:spin/key-value@2.0.0;
    export http-handler;
}

interface http-handler {
    use wasi:http/types@0.2.0.{future-incoming-response};
    set-response: func(url: string, response: future-incoming-response);
}
